# # Starter pipeline
# # Start with a minimal pipeline that you can customize to build and deploy your code.
# # Add steps that build, run tests, deploy, and more:
# # https://aka.ms/yaml

# trigger:
# - main

# pool:
#   vmImage: ubuntu-latest

# steps:
# - script: echo Hello, world!
#   displayName: 'Run a one-line script'

# - script: |
#     echo Add other tasks to build, test, and deploy your project.
#     echo See https://aka.ms/yaml
#   displayName: 'Run a multi-line script'

trigger: none  # Disables automatic triggers on code commits.

resources:
  webhooks:
    - webhook: PortWebhookDeploySAMLIdP
      connection: PortWebhookDeploySAMLIdP

jobs:
- job: DeploySAMLIdP
  steps:
    - script: |
        echo "Webhook triggered by: ${{ parameters.PortWebhookDeploySAMLIdP.client_code }}"
        echo "Client Name: ${{ parameters.PortWebhookDeploySAMLIdP.client_name }}"
        echo "Deploy to Development: ${{ parameters.PortWebhookDeploySAMLIdP.development }}"
        echo "Client Email Domain: ${{ parameters.PortWebhookDeploySAMLIdP.email_domain }}"