name: DORA Pull Request Strategy

on:
  workflow_dispatch:
    inputs:
      your_deployment_integration:
        description: 'Deployment Integration'
        required: true
      your_deployment_type:
        description: 'Deployment Type'
        required: true
      deploy_branch:
        description: 'Deployment Branch'
        required: true
        type: string
      pr_rules_fields:
        description: 'PR Rules Fields'
        required: false
      pr_rules_status_op:
        description: 'Status Operator'
        required: false
        type: string
      pr_rules_status_options:
        description: 'Status Options'
        required: false
        type: string
      pr_rules_author:
        description: 'PR Authors'
        required: false
        type: string
      pr_rules_author_op:
        description: 'Author Operator'
        required: false
        type: string
      pr_rules_label_op:
        description: 'Label Operator'
        required: false
        type: string
      pr_rules_label_str:
        description: 'Label String'
        required: false
        type: string
      pr_rules_repo_op:
        description: 'Repository Operator'
        required: false
        type: string
      pr_rules_repo_str:
        description: 'Repository String'
        required: false
        type: string
      pr_rules_title_op:
        description: 'Title Operator'
        required: false
        type: string
      pr_rules_title_str:
        description: 'Title String'
        required: false
        type: string
      port_context:
        required: true
        description: includes blueprint, run ID, and entity identifier from Port.

jobs:
  trigger-incident:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Inform execution of request to trigger incident
        uses: port-labs/port-github-action@v1
        with:
          clientId: ${{ secrets.PORT_CLIENT_ID }}
          clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
          baseUrl: https://api.getport.io
          operation: PATCH_RUN
          runId: ${{fromJson(inputs.port_context).run_id}}
          logMessage: "About to run pull request DORA strategy..."
