# sonarqube Exporter Workflow
# This workflow responsible for running sonarqube exporter.
# integration.secrets.sonar_api_token: The SonarQube API token used to authenticate with the SonarQube API. SonarQube has 3 types of tokens namely user, project analysis, and global analysis token. We recommend using the user token. To create a user token, see the <a href="https://docs.sonarsource.com/sonarqube/latest/user-guide/user-account/generating-and-using-tokens/" target="_blank">SonarQube documentation</a>
# integration.config.sonar_url: The SonarQube URL to connect to. This is required if you are using SonarQube on-premise. If you are using SonarCloud, the default URL is <a href="https://sonarcloud.io" target="_blank">https://sonarcloud.io</a>
name: Port SonarQube Integration
on: [push]
    # workflow_dispatch:
    # schedule:
    #     - cron: '0 */1 * * *' # Determines the scheduled interval for this workflow. This example runs every hour.

jobs:
    run-integration:
        runs-on: ubuntu-latest

        steps:
            - name: Run sonarqube Integration
              uses: port-labs/ocean-sail@v1
              with:
                type: sonarqube
                port_client_id: ${{ secrets.PORT_CLIENT_ID }}
                port_client_secret: ${{ secrets.PORT_CLIENT_SECRET }}
                port_base_url: "https://api.getport.io"
                integration_identifier: "customer-sonarqube"
                config: |
                    sonar_api_token: ${{ secrets.sonarApiToken }}
                    sonar_url: https://sonarcloud.io
                    sonar_organization_id: ${{ secrets.sonarOrganizationId }}
                    
