name: Rollback ArgoCD Deployment Image

on:
  workflow_dispatch:
    inputs:
      image:
        description: The new image to use for the rollback
        required: true
        type: string
      deployment_path:
        description: Path to where the ArgoCD deployment manifest
        required: true
        type: string
      property_path:
        description: Path to where the deployment image is specified in the deployment manifest
        required: true
        type: string
      should_merge:
        description: Whether the created PR should be merged automatically
        required: true
        type: boolean
      port_payload:
        required: true
        description: >-
          Port's payload, including details for who triggered the action and
          general context (blueprint, run id, etc...)
jobs:
  rollback-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Inform execution of request to rollback deployment image
        uses: port-labs/port-github-action@v1
        with:
          clientId: ${{ secrets.PORT_CLIENT_ID }}
          clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
          baseUrl: https://api.getport.io
          operation: PATCH_RUN
          runId: ${{fromJson(github.event.inputs.port_payload).context.runId}}
          logMessage: "About to rollback deployment image in argocd..."

      - uses: actions/checkout@v3
      - name: Create PR
        id: create-pr
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: '${{ github.event.inputs.deployment_path }}'
          propertyPath: '${{ github.event.inputs.property_path }}'
          value: '${{ github.event.inputs.image }}'
          commitChange: true
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          targetBranch: main
          masterBranchName: main
          createPR: true
          branch: deployment/${{ github.event.inputs.image }}
          message: 'Update Image Version to ${{ github.event.inputs.image }}'
          
      - name: Inform Port about pull request creation status
        uses: port-labs/port-github-action@v1
        with:
          clientId: ${{ secrets.PORT_CLIENT_ID }}
          clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
          baseUrl: https://api.getport.io
          operation: PATCH_RUN
          runId: ${{ fromJson(github.event.inputs.port_payload).context.runId }}
          logMessage: |
            ${{ if eq(steps.create-pr.outcome, 'success') }}
              The creation of PR was successful.
            ${{ else }}
              The creation of PR was not successful.
            ${{ endif }}
          link: '["${{fromJson(steps.create-pr.outputs.pull_request).url}}"]'
  
      - name: Merge Pull Request
        if: ${{ github.event.inputs.should_merge == 'true' && steps.create-pr.outcome == 'success' }}
        env:
          GH_TOKEN: ${{ secrets.MY_PR_GITHUB_TOKEN }}
          PR_URL: ${{ fromJson(steps.create-pr.outputs.pull_request).url }}
        run: |
          HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" \
            -X PUT \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GH_TOKEN" \
            "$PR_URL/merge")

          echo "HTTP Status: $HTTP_STATUS"

          if [ $HTTP_STATUS -eq 200 ]; then
            echo "Pull request merged successfully."
            echo "is_merge_successful=true" >> $GITHUB_ENV
          else
            echo "Failed to merge PR. HTTP Status: $HTTP_STATUS"
            echo "is_merge_successful=false" >> $GITHUB_ENV
          fi

      - name: Inform completion of Argocd rollback into Port
        uses: port-labs/port-github-action@v1
        with:
          clientId: ${{ secrets.PORT_CLIENT_ID }}
          clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
          baseUrl: https://api.getport.io
          operation: PATCH_RUN
          runId: ${{fromJson(github.event.inputs.port_payload).context.runId}}
          logMessage: |
            ${{ if env.is_merge_successful == 'true' }}
              Pull request merged successfully ✅.
            ${{ else }}
              Failed to merge PR
            ${{ endif }}
